/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutPokemonDetailsPNameRouteImport } from './routes/_layout/pokemonDetails/$pName'

const LayoutPokemonSearchIndexLazyRouteImport = createFileRoute(
  '/_layout/pokemonSearch/',
)()
const LayoutAboutIndexLazyRouteImport = createFileRoute('/_layout/about/')()
const LayoutHomeIndexLazyRouteImport = createFileRoute('/_layout/_home/')()

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPokemonSearchIndexLazyRoute =
  LayoutPokemonSearchIndexLazyRouteImport.update({
    id: '/pokemonSearch/',
    path: '/pokemonSearch/',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/pokemonSearch/index.lazy').then((d) => d.Route),
  )
const LayoutAboutIndexLazyRoute = LayoutAboutIndexLazyRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/about/index.lazy').then((d) => d.Route),
)
const LayoutHomeIndexLazyRoute = LayoutHomeIndexLazyRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/_home/index.lazy').then((d) => d.Route),
)
const LayoutPokemonDetailsPNameRoute =
  LayoutPokemonDetailsPNameRouteImport.update({
    id: '/pokemonDetails/$pName',
    path: '/pokemonDetails/$pName',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutHomeIndexLazyRoute
  '/pokemonDetails/$pName': typeof LayoutPokemonDetailsPNameRoute
  '/about/': typeof LayoutAboutIndexLazyRoute
  '/pokemonSearch/': typeof LayoutPokemonSearchIndexLazyRoute
}
export interface FileRoutesByTo {
  '/pokemonDetails/$pName': typeof LayoutPokemonDetailsPNameRoute
  '/': typeof LayoutHomeIndexLazyRoute
  '/about': typeof LayoutAboutIndexLazyRoute
  '/pokemonSearch': typeof LayoutPokemonSearchIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/pokemonDetails/$pName': typeof LayoutPokemonDetailsPNameRoute
  '/_layout/_home/': typeof LayoutHomeIndexLazyRoute
  '/_layout/about/': typeof LayoutAboutIndexLazyRoute
  '/_layout/pokemonSearch/': typeof LayoutPokemonSearchIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemonDetails/$pName' | '/about/' | '/pokemonSearch/'
  fileRoutesByTo: FileRoutesByTo
  to: '/pokemonDetails/$pName' | '/' | '/about' | '/pokemonSearch'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/pokemonDetails/$pName'
    | '/_layout/_home/'
    | '/_layout/about/'
    | '/_layout/pokemonSearch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/pokemonSearch/': {
      id: '/_layout/pokemonSearch/'
      path: '/pokemonSearch'
      fullPath: '/pokemonSearch/'
      preLoaderRoute: typeof LayoutPokemonSearchIndexLazyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about/': {
      id: '/_layout/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof LayoutAboutIndexLazyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_home/': {
      id: '/_layout/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutHomeIndexLazyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pokemonDetails/$pName': {
      id: '/_layout/pokemonDetails/$pName'
      path: '/pokemonDetails/$pName'
      fullPath: '/pokemonDetails/$pName'
      preLoaderRoute: typeof LayoutPokemonDetailsPNameRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutPokemonDetailsPNameRoute: typeof LayoutPokemonDetailsPNameRoute
  LayoutHomeIndexLazyRoute: typeof LayoutHomeIndexLazyRoute
  LayoutAboutIndexLazyRoute: typeof LayoutAboutIndexLazyRoute
  LayoutPokemonSearchIndexLazyRoute: typeof LayoutPokemonSearchIndexLazyRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutPokemonDetailsPNameRoute: LayoutPokemonDetailsPNameRoute,
  LayoutHomeIndexLazyRoute: LayoutHomeIndexLazyRoute,
  LayoutAboutIndexLazyRoute: LayoutAboutIndexLazyRoute,
  LayoutPokemonSearchIndexLazyRoute: LayoutPokemonSearchIndexLazyRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
